@MyRestaurantApi_HostAddress = https://localhost:7293

@contactRoute = /api/Contact
@contentType = application/json

@id = 3

GET https://localhost:7293/api/Contact

###
Get {{MyRestaurantApi_HostAddress}}/api/Contact/3

###
PUT {{MyRestaurantApi_HostAddress}}/api/Contact/3
Content-Type: {{contentType}}

{
  "id": 3,
  "name": "Eline Barstad",
  "email": "elineb@example.com",
  "phone": "555-212-5658"
}

###

POST https://localhost:7293/api/Contact
Content-Type: application/json

{
  "name": "Eline Barstad",
  "email": "elineb@example.com",
  "phone": "555-212-5658"
}

###
GET http://localhost:5192/api/MenuItem/

###

Get {{MyRestaurantApi_HostAddress}}/api/Contact/

###
GET {{MyRestaurantApi_HostAddress}}/api/MenuItemOrdered
###
Get {{MyRestaurantApi_HostAddress}}/api/TogoOrder/

###

Get {{MyRestaurantApi_HostAddress}}/api/TogoOrder/

###

Post {{MyRestaurantApi_HostAddress}}/api/TogoOrder/
Content-Type: application/json

{
  "itemsOrdered": [
    {
      "menuItemId":2001
    }
  ],
  "subtotal": 3.50,
  "tax": 0.8,
  "total": 4.30,
  "paymentMethod": 1,
  "customer": {
    "id": 2
  }
}
###

Post {{MyRestaurantApi_HostAddress}}/api/TogoOrder/
Content-Type: application/json

{
  "itemsOrdered": [
    {
      "menuItemId":2001
    },
    {
      "menuItemId":2002
    },
    {
      "menuItemId":2003
    },
    {
      "menuItemId":2004
    }
  ],
  "subtotal": 33.50,
  "tax": 4.8,
  "total": 38.30,
  "paymentMethod": 1,
  "customer": {
    "id": 3
  }
}

###

Post {{MyRestaurantApi_HostAddress}}/api/TogoOrder/
Content-Type:  application/json

{
  "itemsOrdered": [
    {
      "menuItemId":1001,
      "price": 1.11,
      "category": 1
    },
    {
      "menuItemId":2002
    },
    {
      "menuItemId":1001
    },
    {
      "menuItemId":2003
    },
    {
      "menuItemId":3001
    },
    {
      "menuItemId":2001
    }
  ],
  "subtotal": 15.99,
  "tax": 1.1,
  "total": 17.00,
  "paymentMethod": 2,
  "customer": {
    "id": 2
  }
}

###

GET {{MyRestaurantApi_HostAddress}}/api/MenuItem/

###

Get {{MyRestaurantApi_HostAddress}}/api/TogoOrder/

###
@newmsg = {{Message}}
PUT https://httpbin.org/anything
Content-Type: application/json

{
    "content": "content here",
    "message": {{newmsg}}
}

###

@LocalMessage = {{userDbConnectionString}}/{{ApiKey}}/{{otherSecret}}
@OtherMsg = {{Message}}/

###
PUT https://httpbin.org/anything
Content-Type: application/json

{
    "content": "content here",
    "message": {{Message}}
}
###

# ------------------------------------------------------------------
# reqres.in
# ------------------------------------------------------------------
@reqHost = https://reqres.in
@reqUsername = george.bluth@reqres.in

GET {{reqHost}}/api/users
###

POST https://reqres.in/api/register
Content-Type: application/json

{
  "username": "{{reqUsername}}",
  "email": "hello@example.com",
  "password": "123456"
}

###
POST {{reqHost}}/api/login
Content-Type: application/json

{
  "username": "{{reqUsername}}",
  "email": "{{reqUsername}}",
  "password": "some password"
}

###
GET https://reqres.in/api/{resource}?page=1&per_page=10

###
GET https://reqres.in/api/{resource}/5
###


GET {{MyRestaurantApi_HostAddress}}/api/Contact/

###

GET {{MyRestaurantApi_HostAddress}}/api/Contact/

###

POST {{MyRestaurantApi_HostAddress}}/api/MenuItem/

###
GET https://httpbin.org/headers
X-1Username: {{$processEnv USERNAME}}
X-2ApiSecret: {{$processEnv HOMEDRIVE}}

###
GET https://httpbin.org/headers
X-1RandomInt: {{$randomInt}}
X-2DateTime: {{$datetime iso8601}} 
X-3DateTime: {{$datetime rfc1123}} 
X-4DateTime: {{$datetime rfc1123 1 d}} 
X-5DateTime: {{$datetime "dd-MM-yyyy" 1 y}}
X-6TimeStamp:{{$timestamp}}
X-7TimeStamp:{{$timestamp 1 y}}
X-8LocalDateTime: {{$localDatetime rfc1123}}
X-9LocalDateTime: {{$localDatetime iso8601}}
X-10LocalDateTime: {{$localDatetime iso8601 1 y}}

###


GET https://httpbin.org/basic-auth/user/passwd HTTP/1.1
Authorization: Basic user:passwd
###

GET https://httpbin.org/basic-auth/user/passwd HTTP/1.1
Authorization: Basic dXNlcjpwYXNzd2Q=
###

GET https://httpbin.org/basic-auth/user/passwd HTTP/1.1
Authorization: Basic user passwd
Content-Type: text/plain


###
GET https://httpbin.org/anything?foo=b$filter=Id eq 1ar

###

POST {{MyRestaurantApi_HostAddress}}/api/Contact/

###
