# For more info on HTTP files go to https://aka.ms/vs/httpfile

GET https://localhost:7277/api/MenuItems

###

// populate the MenuItems table
POST https://localhost:7277/api/MenuItems/AddMany
Content-Type: application/json

[
  {
    "name": "Hamburger",
    "price": 3.68,
    "description": "It's a cheese burger without the cheese",
    "category": 1
  },
  {
    "name": "Hamburger - double",
    "price": 5.69,
    "description": "It's a cheese burger without the cheese, with two beef patties",
    "category": 2
  },
  {
    "name":"Cheeseburger",
    "price": 4.09,
    "description": "A hamburger with cheese",
    "category": 2
  },
  {
    "name":"Cheeseburger - double",
    "price": 4.09,
    "description": "A hamburger with cheese, with two beef patties",
    "category": 2
  },
  {
    "name":"Deluxe Cheeseburger",
    "price": 4.39,
    "description": "Cheeseburger with all the toppings",
    "category": 2
  },
  {
    "name":"Deluxe Cheeseburger - double",
    "price": 6.79,
    "description": "Cheeseburger with all the toppings, with two beef patties",
    "category": 2
  },
  {
    "name":"Mushroom & Swiss burger",
    "price": 4.59,
    "description": "Mushroom & Swiss burger",
    "category": 2
  },
  {
    "name":"Mushroom & Swiss burger - double",
    "price": 4.59,
    "description": "Mushroom & Swiss burger, with two beef patties",
    "category": 2
  }
]
###

// populate a few customers in the Contact table
POST https://localhost:7277/api/Contacts/AddMany
Content-Type: application/json

[
  {
    "name": "Sayed Hashimi",
    "email": "sayed@example.com",
    "phone": "555-111-2222"
  },
  {
    "name": "Mads Kristensen",
    "email": "madsk@example.com",
    "phone": "555-111-3333"
  },
  {
    "name": "Eline Barstad",
    "email": "elineb@example.com",
    "phone": "555-111-4444"
  },
  {
    "name": "Theodore Lamy",
    "email": "theol@example.com",
    "phone": "555-111-5555"
  },
  {
    "name": "María Zelaya",
    "email": "mariaz@example.com",
    "phone": "555-111-6666"
  },
  {
    "name": "Kubanychbek Sagynbek",
    "email": "kubans@example.com",
    "phone": "555-111-7777"
  },
  {
    "name": "Denise Bourgeois",
    "email": "deniseb@example.com",
    "phone": "555-111-8888"
  },
  {
    "name": "Robin Danielsen",
    "email": "robind@example.com",
    "phone": "555-111-9999"
  }
]

###

GET https://localhost:7277/api/Contacts

###